name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file

      - name: Run Unit Tests
        run: |
          python -m unittest rectangle_test  # Run rectangle tests
          python -m unittest circle_test      # Run circle tests (ensure this file exists)
          python -m unittest square_test       # Run square tests (ensure this file exists)
          python -m unittest triangle_test     # Run triangle tests (ensure this file exists)
